// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQdF80ncEdE1Rnk1tM3Z5Y8-VH3Pz0mlg',
    appId: '1:902511247218:web:0784dfb75df15af546e7eb',
    messagingSenderId: '902511247218',
    projectId: 'graduproject-9445e',
    authDomain: 'graduproject-9445e.firebaseapp.com',
    storageBucket: 'graduproject-9445e.firebasestorage.app',
    measurementId: 'G-FF67FRW0TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrHVgLJjNJ0S3BR1i9EEQt2373KWj0n0',
    appId: '1:902511247218:android:2cb8b12f1c7cc30846e7eb',
    messagingSenderId: '902511247218',
    projectId: 'graduproject-9445e',
    storageBucket: 'graduproject-9445e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl-QJA6ZrdkzQuha637v9SRxMnnfU7oig',
    appId: '1:902511247218:ios:5b5fe23dfb1291e146e7eb',
    messagingSenderId: '902511247218',
    projectId: 'graduproject-9445e',
    storageBucket: 'graduproject-9445e.firebasestorage.app',
    iosBundleId: 'com.example.gradu2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-QJA6ZrdkzQuha637v9SRxMnnfU7oig',
    appId: '1:902511247218:ios:5b5fe23dfb1291e146e7eb',
    messagingSenderId: '902511247218',
    projectId: 'graduproject-9445e',
    storageBucket: 'graduproject-9445e.firebasestorage.app',
    iosBundleId: 'com.example.gradu2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQdF80ncEdE1Rnk1tM3Z5Y8-VH3Pz0mlg',
    appId: '1:902511247218:web:10a1984338f6f9d646e7eb',
    messagingSenderId: '902511247218',
    projectId: 'graduproject-9445e',
    authDomain: 'graduproject-9445e.firebaseapp.com',
    storageBucket: 'graduproject-9445e.firebasestorage.app',
    measurementId: 'G-8ESW37JS34',
  );

}